### ISSUE TITLE
alternative function definition

### ISSUE THREAD

**Issue by davanessoff-yseop** [yseop/vscode-yseopml#120]
Extract:
```
function ResultsTable::groupIndex(PatientGroupPartition group, {TABLE_OF: Symbol tableTag {__nullable}})
--> local Collection groups
```

1. arguments declaration, with optional arguments (a lot of those can be found in `libActors`)
2. `local` introduced with `--> `

**Comment by alacambre-yseop** [comment]
Sorry, but it seems that it is working with version `1.6.3`
![image](https://user-images.githubusercontent.com/15327919/62030860-47ff0300-b1e6-11e9-9ba2-11b4de7205be.png)

**Comment by davanessoff-yseop** [comment]
Yet, I'm on `1.6.3` and have still issues:
`extraneous input 'groups' expecting {';', '-->', '==>', '---', '+++'}`

**Comment by davanessoff-yseop** [comment]
Seems it's working, the parser indicates errors at the `local` level if there is an issue below.
