### ISSUE TITLE
`applyCollectionOn` management

### ISSUE THREAD

**Issue by davanessoff-yseop** [yseop/vscode-yseopml#121]
Extract:
```
Function SentenceGenerator::getUniqueConcepts
args {}
--> return applyCollectionOn(_dataStructure in this.getDataStructures(), select _dataStructure.filterConcept).toOrderedSet()
;
```
It seems the parser doesn't take this instruction into account.

**Comment by alacambre-yseop** [comment]
It doesn't know the `select` keywork in this context.

**Comment by davanessoff-yseop** [comment]
> It doesn't know the `select` keyword in this context.

I can give you more examples of usage of applyCollectionOn if you want

**Comment by davanessoff-yseop** [comment]
[https://github.com/yseop/yseop-engine/blob/40875809c1297ad07a8d62fbe9a0a1c35d92523c/tests/collection/applyCollection/applyCollection.kao](url)

**Comment by davanessoff-yseop** [comment]
[https://github.com/yseop/yseop-engine/blob/master/tests/collection/applyCollection/applyCollection.kao](url)
