### ISSUE TITLE
`rename` management

### ISSUE THREAD

**Issue by davanessoff-yseop** [yseop/vscode-yseopml#127]
Here is a sample of a `rename` instruction:
`rename pt to ptLanguage forClass MultilingualExpression`

the structure is
`rename <elt1> to <elt2> forClasss <className>`

**Comment by davanessoff-yseop** [comment]
This instruction is quite useful when you have name conflicts in a multiclass inherited class.

**Comment by alacambre-yseop** [comment]
What are `elt1` and `elt2`? Just ids?

**Comment by alacambre-yseop** [comment]
Also, what are the correct places to put this instruction?

**Comment by davanessoff-yseop** [comment]
> What are `elt1` and `elt2`? Just ids?

Not really, it can be anything, like `pt` is the name of an attribute whereas it has `MultivaluedExpression::pt` as an id

**Comment by alacambre-yseop** [comment]
OK. For our grammar it's the same :smile:

**Comment by davanessoff-yseop** [comment]
> Also, what are the correct places to put this instruction?

Anywhere, like it is for `extern` declaration or `function` instruction
