### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by ahelman-yseop** [yseop/vscode-yseopml#32]
when commenting the code with '//', the color doesn't always change to green 
(sometimes the // is yellow, and the commented code, blue

![comment](https://user-images.githubusercontent.com/39375956/44472269-1a9cf300-a62e-11e8-9aa9-76630d56e2d1.png)

**Comment by alacambre-yseop** [comment]
Can you add a screenshot and/or tell us what color theme you're using?
