### ISSUE TITLE
“local” keyword highlighting

### ISSUE THREAD

**Issue by mminot-yseop** [yseop/vscode-yseopml#78]
When writing functions, the `local` keyword used for the local variable declaration block is not highlighted, whereas the `static` one is.

![image](https://user-images.githubusercontent.com/36635838/53794934-3106fe00-3f31-11e9-9f74-111e8065674f.png)

### Expected
Similar style for `local` and `static` in this context.

### What happens
`local` has the default colour, while `static` is OK.

### Sample code

```
function printXMLSchema(Class MyClass)
local {
	Integer foo
}
static {
	StringBuffer sb
		--> maxSize 100000
	;
}
--> local XmlStream xs
--> domains String
--> action {
	xs = new(XmlStream);
}
;
```

**Comment by alacambre-yseop** [comment]
@mminot-yseop I close this issue since version 1.5.0 fixes it.
