### ISSUE TITLE
Parsing of implementation area

### ISSUE THREAD

**Issue by davanessoff-yseop** [yseop/vscode-yseopml#94]
I just give you an example and let you check the problems detected by the extension at the moment:
```
implementation SentenceToGenerate

	forGroups
	--> defaultValue theClinicalStudy.groupsOfSubjects
	
	override {
		write function
	}
;
```
I will give you other examples when I stumble upon some.

**Comment by alacambre-yseop** [comment]
@davanessoff-yseop Fix should be available with #96.
