### ISSUE TITLE
Incorrect error rising at Explicit HashMap

### ISSUE THREAD

**Issue by dhoyos-yseop** [yseop/vscode-yseopml#99]
The yml extension marks as an error some hashmaps, for example those where the keys are numbers.
![image](https://user-images.githubusercontent.com/44225796/59111593-ef5a6a80-8906-11e9-9011-712c36b12e2b.png)

**Comment by alacambre-yseop** [comment]
@dhoyos-yseop You're right. :thinking: 
It seems that the parser we're using accepts only some specific kind of keys. We'll upgrade it soon.
